version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: lending-borrowing-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lending-borrowing
      POSTGRES_DB: lending-borrowing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lending_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: lending-borrowing-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - lending_network

volumes:
  postgres_data:

networks:
  lending_network:
    driver: bridge
